### ISSUE TITLE
Seems rather limited

### ISSUE THREAD

**Issue by mattjohnsonpint** [runspired/Date.toString.js#1]
First, let me say that I applaud your attempt.  JavaScript is really awful when it comes to this time zones and date/time in general.  I understand and agree with the need for a library such as this.  So I hope you don't read any hostility into my feedback.  It is meant as constructive criticism only.

There are a lot of assumptions being made in your implementation.  First, the [Olson/IANA TZDB](http://www.iana.org/time-zones) is constantly being updated, and you only have a partial implementation - yet this seems to be targeted as a general purpose / static library. Are you prepared to keep it updated?  Are you going to provide a mechanism for the user of your library to update it?  There were 10 releases of the TZDB just last year alone.  There is _already_ a good javascript implementation of this database called [TimezoneJS](https://github.com/mde/timezone-js) which provides a full implementation of the TZDB, and provides a mechanism for keeping it updated.

Second, it seems most of your timezone specific code comes from [jsTimeZoneDetect](https://bitbucket.org/pellepim/jstimezonedetect) - which is a great library, but was designed for a specific purpose - to attempt to pick an Olson timezone id that is meaningful to the current user - _as of now_.  By using this as an authoritative source, you have locked the user down to the rules as they currently exist.  For example, you have a list of `dst_starts` - but this list has changed _many_ times in the past, and will change _many_ times in the future.  You cannot just compare the month/day from any date provided against this list.  In many cases, it will be wrong.

Also, jsTimeZoneDetect is not comprehensive.  It only has a small subset of time zones, and it makes a lot of assumptions.  You should carefully read the _limitations_ section on their overview page.  You seem to have ignored much of that.

Lastly, there is already a much more comprehensive and mature library for doing all of the non-timezone stuff, [Moment.js](http://momentjs.com/).  There's only a few things they don't handle well (IMHO):
- Usage of timezones (but they are _working_ on that [here](https://github.com/timrwood/moment-timezone))
- Using the offset meaningfully (which I have opened an issue for [here](https://github.com/timrwood/moment/issues/611))

All of the stuff you are doing with string formatting is handled with their `.format()` method, and they are also handling parsing, among other things.

Best wishes - and again, thanks for the attempt.

**Comment by runspired** [comment]
I will be maintaining the start list, as this code is actually actively bound to a 'standard.js' library I use at my company, but the last few weeks have been hectic (we're launching a new app) and I haven't had the time to review the current Olson lists to see if I couldn't improve upon jsTimezoneDetect (whose code is rather similar to TimezoneJS I've noticed, but with a more abbreviated list).

What I will be doing is implementing two version "abbreviated list" version and a "comprehensive list" version, the reason being that file size can be an issue and the comprehensive Olson list is large.  The abbreviated list will be similar to what is there now, the "best choices" from various regions, while the extended list will contain everything.

**Comment by runspired** [comment]
I didn't know about Moment.js, but it looks really lovely.  I may end up contributing some efforts there.  A few of the primary features I will be adding here are fast access to SQL Date and Datetime formats, as well as a "time since" feature (ala '2min ago', 'just now', '10 days ago').

**Comment by mattjohnsonpint** [comment]
Yeah, that's pretty much what Moment.js is all about.  They certainly could use more contributors. :)

TimezoneJS actually doesn't come with a list at all.  They work off of the raw TZDB files.  So updating it means just dropping in the new files.  They also have some server-side scripts that you can run to pre-parse the files and provide the data as json instead.

I strongly discourage you from manually trying to sort out the olson lists yourself.  It's a vast effort with hundreds of contributors around the globe.  If you know where your app will be used, you could narrow the scope a bit by not including the entire list.  But I would filter by continent, not by going in and pulling out things you don't think hold value.  They ultimately will to _someone_ and they will be upset when they can't use your product.  Especially as a library - you can't expect to know up front how everyone using your code will want to use it.

**Comment by mattjohnsonpint** [comment]
FYI - I now highly recommend [moment-timezone](http://momentjs.com/timezone) over TimeZoneJS.  The latter has many unresolved bugs, especially near DST transitions.

**Comment by runspired** [comment]
@mj1856 agreed, I almost exclusively use moment and moment-timezone now.  I should probably add an "unmaintained" badge to this as I don't think I'll be coming back to it now that tree-shaking is largely a thing and micro-libs don't matter as much.

**Comment by runspired** [comment]
@mattjohnsonpint I'd forgotten this thing even existed at this point, wow does time fly

**Comment by mattjohnsonpint** [comment]
https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories

😉
